_target_: disco.lightning.modules.Autoencoder
in_channels: ${dataset.num_channels}
img_size: ${dataset.img_size}
channels: [512, 256, 128, 64, 32, 16]
backbone: resnet18
buffer_chunk_size: 48
lr: ${training.lr}
shapes_per_task: ${dataset.shapes_per_task}